from django.urls import path, include
from . import views
urlpatterns = [
    path('',views.home, name="home"),
    path('<int:year>/<str:month>/', views.home, name="home"),
    path('events', views.all_events, name="list-events"),
    path('add_venue', views.add_venue, name="add-venue"),
    path('list_venue', views.list_venues, name="list-venues"),
    path('show_venue/<venue_id>', views.show_venues, name="show-venue"),
    path('search_venue', views.search_venues, name="search-venues"),
    path('search/', views.search_event, name="search-event"),
    path('update_venue/<venue_id>', views.update_venue, name="update-venue"),
    path('update_event/<event_id>', views.update_event, name="update-event"),
    path('add_event', views.add_event, name="add-event"),
    path('delete_event/<event_id>', views.delete_event, name="delete-event"),
    path('delete_venue/<venue_id>', views.delete_venue, name="delete-venue"),
    path('venue_text', views.venue_text, name='venue_text'),
    path('venue_csv', views.venue_csv, name='venue_csv'),
    path('venue_json', views.venue_json, name='venue_json'),
    path('venue_pdf', views.venue_pdf, name='venue_pdf'),
    path('my_events', views.my_events, name='my_events'),
    path('admin_approval', views.admin_approval, name='admin_approval'),
    path('venue_event/<venue_id>', views.venue_events, name="venue-events"),
    path('show_event/<event_id>', views.show_event, name="show-event"),
]
